# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grammes.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
from PyQt5.QtWidgets import QVBoxLayout, QPushButton

class Ui_DiathesimaEishthria(object):
    def loadData(self):
        cnx = mysql.connector.connect(host="remotemysql.com", user="4Re4u1cLi1", password="Gto4QD5Kx7",database="4Re4u1cLi1")
        mycursor = cnx.cursor()
        mycursor.execute("SELECT DISTINCT Εισιτήριο.`κωδ.εισιτηρίου`,Αφορά.`κωδ.θέσης` FROM (Αφορά JOIN Εισιτήριο ON Εισιτήριο.`κωδ.εισιτηρίου`=Αφορά.`κωδ.εισιτηρίου`) WHERE `διαθεσιμότητα` LIKE 'ΝΑΙ'")
        result = mycursor.fetchall()
        self.tableWidget.setRowCount(0)

        for row_number, row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number,data in enumerate(row_data):
                self.tableWidget.setItem(row_number,column_number, QtWidgets.QTableWidgetItem(str(data)))

        cnx.close()

    def metra(self):
        cnx = mysql.connector.connect(host="remotemysql.com", user="4Re4u1cLi1", password="Gto4QD5Kx7",database="4Re4u1cLi1")
        mycursor = cnx.cursor()
        mycursor.execute("SELECT COUNT(`κωδ.εισιτηρίου`) FROM Εισιτήριο WHERE `διαθεσιμότητα` LIKE 'ΝΑΙ'")
        result = mycursor.fetchall()

        for i in result:
            print(i)

    def setupUi2(self, MainWindow):
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget_new")

        MainWindow.setCentralWidget(self.centralwidget)

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 11, 621, 531))
        #self.tableWidget.setRowCount(19)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)

        self.loadData()

        self.Plithos = QtWidgets.QPushButton(self.centralwidget)
        self.Plithos.setGeometry(QtCore.QRect(340, 130, 75, 23))
        self.Plithos.setObjectName("btn_load")
        self.Plithos.clicked.connect(self.metra)  # FORTWSE TOUS PELATES

        self.retranslateUi2(MainWindow)

    def retranslateUi2(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        _translate = QtCore.QCoreApplication.translate
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Κωδικός Εισητηρίου"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Κωδικός Θέσης"))

        self.Plithos.setText(_translate("MainWindow", "Πλήθος"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    OtherWindow = QtWidgets.QMainWindow()
    ui = Ui_DiathesimaEishthria()
    ui.setupUi2(OtherWindow)
    OtherWindow.show()
    sys.exit(app.exec_())
