# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_Dialog(object):

    def addPelath(self):
        ΑΔΤ:""
        ονοματεπώνυμο:""
        email:""

        ΑΔΤ=self.lineEdit.text()
        ονοματεπώνυμο=self.lineEdit_2.text()
        email=self.lineEdit_3.text()

        ticket_code=self.lineEdit_4.text()
        hmeromhnia = self.comboBox.itemText(self.comboBox.currentIndex())
        kathgoria = self.comboBox_2.itemText(self.comboBox_2.currentIndex())

        cnx = mysql.connector.connect(host="remotemysql.com", user="4Re4u1cLi1", password="Gto4QD5Kx7",database="4Re4u1cLi1")
        mycursor = cnx.cursor()
        mycursor.execute("INSERT INTO Πελάτης VALUES (%s,%s,%s)", (ΑΔΤ,ονοματεπώνυμο,email))
        mycursor.execute("UPDATE Εισιτήριο SET διαθεσιμότητα='ΟΧΙ' WHERE `κωδ.εισιτηρίου`="+str(ticket_code))
        cnx.commit()

        cnx.close()

    def Epituxia(self):
        msg=QtWidgets.QMessageBox()
        msg.setWindowTitle("Mhnuma")
        msg.setText("Epituxhs prosthikh")
        x=msg.exec_()

    def setupUi4(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 456)
        Dialog.setStyleSheet("background-color: rgb(93, 0, 0);")

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 60, 361, 31))
        self.label.setStyleSheet("colour:rgb(137, 244, 255);\n"
"font-size:28pt;")
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 160, 51, 21))
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 120, 47, 13))
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(90, 200, 47, 13))
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(90, 250, 61, 16))
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(90, 280, 51, 16))
        self.label_6.setObjectName("label_6")

        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(220, 280, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(200, 120, 113, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 160, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 200, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.Krathsh = QtWidgets.QPushButton(Dialog)
        self.Krathsh.setGeometry(QtCore.QRect(210, 410, 75, 23))
        self.Krathsh.setObjectName("pushButton")
        self.Krathsh.clicked.connect(self.addPelath)
        self.Krathsh.clicked.connect(self.Epituxia)


        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(90, 320, 51, 16))
        self.label_7.setObjectName("label_7")

        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(220, 320, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")

        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 250, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", " ΠΡΟΣΘΗΚΗ ΠΕΛΑΤΗ"))
        self.label_2.setText(_translate("Dialog", "Όνομα:"))
        self.label_3.setText(_translate("Dialog", "Α.Δ.Τ.:"))
        self.label_4.setText(_translate("Dialog", "e-mail:"))
        self.label_5.setText(_translate("Dialog", "Ticket_code:"))
        self.label_6.setText(_translate("Dialog", "Προβολή:"))
        self.comboBox.setItemText(0, _translate("Dialog", "02/01/2014"))
        self.comboBox.setItemText(1, _translate("Dialog", "03/01/2014"))
        self.Krathsh.setText(_translate("Dialog", "ΚΡΑΤΗΣΗ"))
        self.label_7.setText(_translate("Dialog", "Κατηγορία:"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "κανονικό "))
        self.comboBox_2.setItemText(1, _translate("Dialog", "φοιτητικό"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "κάτω των 18"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi4(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
