# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grammes.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
from PyQt5.QtWidgets import QVBoxLayout, QPushButton
# from OtherWindow import Ui_OtherWindow
from Pelates import *
from DiathesimaEishthria import *
from parastaseis import *
from insert import *

class Ui_MainWindow(object):

    def ListaPelatwn(self):

        self.window = QtWidgets.QMainWindow()
        ui = Ui_OtherWindow()
        ui.setupUi1(self.window)
        self.window.show()

    def ListaDiathesimwnEishthriwn(self):

        self.window = QtWidgets.QMainWindow()
        ui = Ui_DiathesimaEishthria()
        ui.setupUi2(self.window)
        self.window.show()

    def ListaProvolwn(self):

        self.window = QtWidgets.QMainWindow()
        ui = Ui_Parastaseis()
        ui.setupUi3(self.window)
        self.window.show()

    def KaneKrathsh(self):
        self.window = QtWidgets.QMainWindow()
        ui = Ui_Dialog()
        ui.setupUi4(self.window)
        self.window.show()


    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        self.photox = QtWidgets.QLabel(self.centralwidget)
        self.photox.setGeometry(QtCore.QRect(-30, -10, 841, 441))
        self.photox.setText("")
        self.photox.setPixmap(QtGui.QPixmap("3346db86296ad3797368bb631c52e70b_XL.jpg"))
        self.photox.setScaledContents(True)
        self.photox.setObjectName("photox")


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.Pelates = QtWidgets.QPushButton(self.centralwidget)
        self.Pelates.setGeometry(QtCore.QRect(340, 130, 75, 23))
        self.Pelates.setObjectName("btn_load")
        self.Pelates.clicked.connect(self.ListaPelatwn)  # FORTWSE TOUS PELATES

        self.Eishthria = QtWidgets.QPushButton(self.centralwidget)
        self.Eishthria.setGeometry(QtCore.QRect(260, 180, 251, 23))
        self.Eishthria.setObjectName("Eishthria")
        self.Eishthria.clicked.connect(self.ListaDiathesimwnEishthriwn)  # FORTWSE TA DIATHESIMA EISHTHRIA

        self.Parastaseis = QtWidgets.QPushButton(self.centralwidget)
        self.Parastaseis.setGeometry(QtCore.QRect(340, 220, 75, 23))
        self.Parastaseis.setObjectName("Eishthria")
        self.Parastaseis.clicked.connect(self.ListaProvolwn)  # FORTWSE TIS PROVOLES

        self.Krathsh = QtWidgets.QPushButton(self.centralwidget)
        self.Krathsh.setGeometry(QtCore.QRect(340, 260, 75, 23))
        self.Krathsh.setObjectName("Eishthria")
        self.Krathsh.clicked.connect(self.KaneKrathsh)  # FORTWSE TIS PROVOLES

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
         _translate = QtCore.QCoreApplication.translate
         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
         self.Pelates.setText(_translate("MainWindow", "Πελάτες"))
         self.Eishthria.setText(_translate("MainWindow", "Διαθέσιμα Εισητήρια/Θέσεις"))
         self.Parastaseis.setText(_translate("MainWindow", "Παραστάσεις"))
         self.Krathsh.setText(_translate("MainWindow", "ΚΡΑΤΗΣΗ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
